events {}

http {
  include       mime.types;
  default_type  application/octet-stream;
  sendfile      on;
  keepalive_timeout  65;

  # gzip básico
  gzip on;
  gzip_types text/plain text/css application/javascript application/json image/svg+xml;
  gzip_min_length 1024;

  server {
    listen 80;
    server_name _;

    # Pasta onde os arquivos serão servidos
    root /usr/share/nginx/html;
    index index.html;

    # Cache leve para estáticos
    location ~* \.(css|js|png|jpg|jpeg|gif|svg)$ {
      expires 7d;
      add_header Cache-Control "public, max-age=604800";
      try_files $uri =404;
    }

    # HTML sem cache agressivo
    location ~* \.(html)$ {
      expires -1;
      add_header Cache-Control "no-cache";
      try_files $uri =404;
    }

    # fallback genérico (se quiser SPA, troque para try_files $uri /index.html;)
    location / {
      try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
  }
}
